import type { EditorThemeClasses } from "lexical";

const theme: EditorThemeClasses = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "editor-placeholder",
  paragraph: "mb-2 last:mb-0",
  quote: "border-l-4 border-muted pl-4 italic my-2",
  heading: {
    h1: "text-3xl font-bold mb-4 mt-6",
    h2: "text-2xl font-bold mb-3 mt-5",
    h3: "text-xl font-bold mb-2 mt-4",
    h4: "text-lg font-bold mb-1 mt-3",
    h5: "text-base font-bold mb-1 mt-2",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal ml-6 mb-2",
    ul: "list-disc ml-6 mb-2",
    listitem: "mb-1",
  },
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-muted px-1.5 py-0.5 rounded-sm font-mono text-sm",
  },
  code: "bg-muted p-4 rounded-md font-mono text-sm block my-2 overflow-x-auto",
  codeHighlight: {
    atrule: "text-blue-600",
    attr: "text-blue-600",
    boolean: "text-red-600",
    builtin: "text-green-600",
    cdata: "text-gray-500",
    char: "text-green-600",
    class: "text-blue-600",
    "class-name": "text-blue-600",
    comment: "text-gray-500",
    constant: "text-red-600",
    deleted: "text-red-600",
    doctype: "text-gray-500",
    entity: "text-yellow-600",
    function: "text-blue-600",
    important: "text-red-600",
    inserted: "text-green-600",
    keyword: "text-purple-600",
    namespace: "text-blue-600",
    number: "text-red-600",
    operator: "text-yellow-600",
    prolog: "text-gray-500",
    property: "text-red-600",
    punctuation: "text-gray-600",
    regex: "text-yellow-600",
    selector: "text-green-600",
    string: "text-green-600",
    symbol: "text-red-600",
    tag: "text-red-600",
    url: "text-yellow-600",
    variable: "text-orange-600",
  },
};

export default theme;
