name: Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      ts_check: ${{ steps.filter.outputs.ts_check }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ts_check:
              - '**/*.ts'
              - '**/*.tsx'
              - 'deno.json'
              - 'deno.lock'

  type-check:
    name: TS Type Check
    needs: filter
    if: needs.filter.outputs.ts_check == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run Type Check
        run: deno task type-check
